### ISSUE TITLE
Неверная логика поиска игры определенного жанра, в которую играли больше времени

### ISSUE THREAD

**Issue by qadodov** [Maxxx1254/GameStore#3]
# Описание

При поиске игры с любым жанром, в которую играли больше времени, результатом всегда возвращается null, вне зависимости от того, играли в игры искомого жанра или нет.

# Локация дефекта

https://github.com/Maxxx1254/GameStore/blob/5217ad6299b25898b0fd4a7b7db87224abfd2cd4/src/main/java/ru/netology/Player.java#L60

# Шаги воспроизведения

1. Открыть [Код программы](https://github.com/Maxxx1254/GameStore/tree/bug_in_Player) в IDEA
2. Запустить тест shouldReturnMostPlayedGameByGenre
3. Посмотреть на выводы в консоли

*Ожидаемые результат:* тест проходит (assertEquals уведомляет о равенстве объектов expected и actual) 
*Фактический результат:* Тест не проходит, в консоли ошибка:
org.opentest4j.AssertionFailedError: 
Expected :ru.netology.Game@42ad22b3
Actual   :null

# Скриншот

![playerBug](https://user-images.githubusercontent.com/99784433/169686412-54fb690b-9a41-4426-8270-e5fea2f1677f.png)

# Окружение

* **Операционная система:** Windows 8.1
*  **IDE:** IntelliJ IDEA 2021.3.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Maxxx1254** [comment]
дополнил метод расчетами для определения популярной игры
