### ISSUE TITLE
При игре в установленную игру количество проигранных часов в маппинге игрока не изменяется

### ISSUE THREAD

**Issue by qadodov** [Maxxx1254/GameStore#4]
# Описание

Количество часов проигранных в установленную игру в маппинге игрока не прибавляется к уже проигранному в данной игре времени. Значение проведенных часов в игре всегда остается 0 (задается при установке).

# Локация дефекта

https://github.com/Maxxx1254/GameStore/blob/5217ad6299b25898b0fd4a7b7db87224abfd2cd4/src/main/java/ru/netology/Player.java#L40

# Шаги воспроизведения

1. Открыть [Код программы](https://github.com/Maxxx1254/GameStore/tree/bug_in_Player) в IDEA
2. Запустить тест shouldSumHoursPlayedInOneGame
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит (assertEquals выдает 50, 50)
*Фактический результат:* Тест не проходит с ошибкой:
org.opentest4j.AssertionFailedError: 
Expected :50
Actual   :0

# Скриншот
![playerBug2](https://user-images.githubusercontent.com/99784433/169688655-23113746-1074-425f-9a47-57d5e11a4c6e.png)

# Окружение
* **Операционная система:** Windows 8.1
* **IDE:** IntelliJ IDEA 2021.3.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Maxxx1254** [comment]
Дополнил метод,

**Comment by Maxxx1254** [comment]
Дополнил метод,
