### ISSUE TITLE
RuntimeException не выкидывается при попытке поиграть в неустановленную игру

### ISSUE THREAD

**Issue by qadodov** [Maxxx1254/GameStore#5]
# Описание

При попытке поиграть в игру, которая не была прежде установлена RuntimeException не выкидывается. Данной инструкции в методе нет.

# Локация дефекта

https://github.com/Maxxx1254/GameStore/blob/5217ad6299b25898b0fd4a7b7db87224abfd2cd4/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения

1. Открыть [Код программы](https://github.com/Maxxx1254/GameStore/tree/bug_in_Player) в IDEA
2. Запустить тест shouldThrowExceptionIfPlayGameThatIsNotInstalled
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит (выкидывается RuntimeException)
*Фактический результат:* Тест не проходит с ошибкой:
org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот

![playerBug3](https://user-images.githubusercontent.com/99784433/169688977-bbdca16f-fdc0-40ff-8717-6461a81b64e1.png)

# Окружение
* **Операционная система:** Windows 8.1
*  **IDE:** IntelliJ IDEA 2021.3.3 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Maxxx1254** [comment]
Добавил классс и метод для вызова данной ошибки
